### ISSUE TITLE
sd: Unable to access 'curl'

### ISSUE THREAD

**Issue by daviddekoning** [whoek/scrumdog#1]

**Comment by daviddekoning** [comment]
When I run scrumdog in PowerShell or Command Prompt, I get the following error:

```
sd: Unable to access 'curl'
    Please report this issues
```

Weirdly, I am able to run curl in both PowerShell and Command Prompt.

I am using Windows 10 enterprise, 10.0.19044. Please let me know if you would like any other info!

**Comment by whoek** [comment]
@daviddekoning  -- Many Thanks for testing it and creating the issue. 
Yip it is an error when app is trying to run curl on local machine.
So far I have tested it on multiple PC's but they all were "Windows 10 Pro" machines only.
Let me have a look and I will let you know when I uploaded a more recent version.
Regards

**Comment by whoek** [comment]
@daviddekoning   -- 

I have: done some more testing, including on a clean install of Microsoft Windows Server 2019 Datacenter.  Unfortunately I don't have access to a Windows 10 Enterprise version.   Could not find an error but I did clean up and added better/more error messaging.   So it might give a better clue on what is the reason.

New version loaded on [scrumdog.app](https://scrumdog.app/) - version 0.3 (build 497)  - if you don't mind try this one.

Many Thanks
Willem

**Comment by whoek** [comment]
@daviddekoning    I have made some changes to `scrumdog` so that it does not rely on `curl` any more. You may want to try it again.   The latest downloads are available from [here](https://github.com/whoek/scrumdog-binaries).
Thanks
